export interface CatalogItem {
  name: string;
  unit: string;
  altUnits?: string[];
}

export interface CatalogCategory {
  id: string;
  label: string;
  emoji: string;
  color: string;
  borderColor: string;
  items: CatalogItem[];
}

export const EXPENSE_CATALOG: CatalogCategory[] = [
  {
    id: "vegetables",
    label: "Vegetables",
    emoji: "🥦",
    color: "bg-green-100 text-green-800",
    borderColor: "border-green-300",
    items: [
      { name: "Potato (Aloo)", unit: "kg" },
      { name: "Sweet Potato (Shakarkand)", unit: "kg" },
      { name: "Yam / Suran (Jimikand)", unit: "kg" },
      { name: "Elephant Foot Yam (Ol)", unit: "kg" },
      { name: "Colocasia / Arbi (Saru)", unit: "kg" },
      { name: "Radish (Mooli)", unit: "kg" },
      { name: "Carrot (Gajar)", unit: "kg" },
      { name: "Beetroot (Chukandar)", unit: "kg" },
      { name: "Turnip (Shalgam)", unit: "kg" },
      { name: "Pointed Gourd (Potala / Parwal)", unit: "kg" },
      { name: "Bottle Gourd (Lauki)", unit: "kg" },
      { name: "Bitter Gourd (Karela)", unit: "kg" },
      { name: "Ridge Gourd (Turai)", unit: "kg" },
      { name: "Snake Gourd (Chichinda)", unit: "kg" },
      { name: "Ash Gourd / Petha", unit: "kg" },
      { name: "Ivy Gourd (Kundru / Tindora)", unit: "kg" },
      { name: "Pumpkin (Kaddu)", unit: "kg" },
      { name: "Spine Gourd (Kantola)", unit: "kg" },
      { name: "Tomato", unit: "kg" },
      { name: "Brinjal / Eggplant (Baigana)", unit: "kg" },
      { name: "Lady Finger / Okra (Bhindi)", unit: "kg" },
      { name: "Green Chilli (Hari Mirch)", unit: "kg" },
      { name: "Capsicum / Bell Pepper (Shimla Mirch)", unit: "kg" },
      { name: "Raw Papaya (Kachha Papaya)", unit: "kg" },
      { name: "Raw Mango (Kachha Aam)", unit: "kg" },
      { name: "Raw Banana (Kachha Kela / Kancha Kadali)", unit: "kg" },
      { name: "Jackfruit (Kathal / Pita)", unit: "kg" },
      { name: "Breadfruit", unit: "kg" },
      { name: "Cabbage (Bandh Gobhi)", unit: "kg" },
      { name: "Cauliflower (Phool Gobhi)", unit: "kg" },
      { name: "Knol Khol (Ganth Gobhi)", unit: "kg" },
      { name: "Broccoli", unit: "kg" },
      { name: "Spinach (Palak)", unit: "kg" },
      { name: "Fenugreek Leaves (Methi Saag)", unit: "bundle", altUnits: ["kg"] },
      { name: "Mustard Leaves (Sarson Saag)", unit: "kg" },
      { name: "Amaranth Leaves (Lal Saag / Khada Saag)", unit: "kg" },
      { name: "Sorrel Leaves (Khatta Saag / Chuka)", unit: "kg" },
      { name: "Water Spinach (Kalmi Saag)", unit: "bundle", altUnits: ["kg"] },
      { name: "Colocasia Leaves (Saru Patra / Arbi Patta)", unit: "bundle", altUnits: ["kg"] },
      { name: "Drumstick Leaves (Munga Saga / Sahjan Patta)", unit: "bundle", altUnits: ["kg"] },
      { name: "Coriander Leaves (Dhania Patta)", unit: "bundle", altUnits: ["kg"] },
      { name: "Mint Leaves (Pudina)", unit: "bundle", altUnits: ["kg"] },
      { name: "Curry Leaves (Kadipatta)", unit: "bundle", altUnits: ["kg"] },
      { name: "Banana Flower (Kela Phool / Kadali Phula)", unit: "pcs", altUnits: ["kg"] },
      { name: "Banana Stem (Kela Thana)", unit: "kg" },
      { name: "Lotus Root (Kamal Kakdi / Padma Mula)", unit: "kg" },
      { name: "Green Peas (Matar)", unit: "kg" },
      { name: "French Beans", unit: "kg" },
      { name: "Cluster Beans (Guar Phali)", unit: "kg" },
      { name: "Broad Beans (Sem)", unit: "kg" },
      { name: "Drumstick (Sahjan / Munga)", unit: "kg" },
      { name: "Onion (Pyaz)", unit: "kg" },
      { name: "Garlic (Lehsun)", unit: "kg" },
      { name: "Ginger (Adrak)", unit: "kg" },
      { name: "Spring Onion (Hara Pyaz)", unit: "bundle", altUnits: ["kg"] },
      { name: "Leek", unit: "kg" },
      { name: "Raw Turmeric (Kachha Haldi)", unit: "kg" },
      { name: "Corn / Maize (Makka)", unit: "pcs", altUnits: ["kg"] },
      { name: "Cucumber (Khira)", unit: "kg" },
      { name: "Pea Shoots", unit: "bundle" },
      { name: "Neem Leaves (Neem Patta)", unit: "bundle" },
      // Citrus & Fruits used as vegetables
      { name: "Lemon (Nimbu)", unit: "kg", altUnits: ["pcs"] },
      { name: "Raw Lemon (Green Nimbu)", unit: "kg" },
      { name: "Amla (Indian Gooseberry)", unit: "kg" },
      // Mushrooms & Exotic
      { name: "Mushroom (Button)", unit: "kg" },
      { name: "Oyster Mushroom", unit: "kg" },
      { name: "Baby Corn", unit: "kg", altUnits: ["pcs"] },
      { name: "Zucchini / Courgette", unit: "kg" },
      { name: "Celery", unit: "bundle", altUnits: ["kg"] },
      { name: "Asparagus", unit: "kg" },
      { name: "Cherry Tomato", unit: "kg" },
      { name: "Water Chestnut (Singhara)", unit: "kg" },
      // Odisha special
      { name: "Bamboo Shoot (Bans Korali)", unit: "kg" },
      { name: "Jackfruit Seeds (Katha Bichi)", unit: "kg" },
      { name: "Papaya Flower (Papita Phool)", unit: "pcs", altUnits: ["kg"] },
      { name: "Taro Stem (Saru Dandi)", unit: "bundle" },
      { name: "Fiddlehead Fern (Dheki Saag)", unit: "bundle", altUnits: ["kg"] },
      { name: "Kokum (Gamboge)", unit: "kg" },
      { name: "Elephant Apple (Ou / Chalta)", unit: "kg" },
      { name: "Raw Tomato (Green)", unit: "kg" },
      { name: "Field Beans (Chawli Phali)", unit: "kg" },
    ],
  },

  {
    id: "grocery",
    label: "Grocery",
    emoji: "🛒",
    color: "bg-yellow-100 text-yellow-800",
    borderColor: "border-yellow-300",
    items: [
      { name: "Mustard Oil (Sarso Tel)", unit: "litre", altUnits: ["ml"] },
      { name: "Sunflower Oil", unit: "litre", altUnits: ["ml"] },
      { name: "Refined Oil", unit: "litre", altUnits: ["ml"] },
      { name: "Coconut Oil", unit: "litre", altUnits: ["ml"] },
      { name: "Groundnut Oil (Moongphali Tel)", unit: "litre", altUnits: ["ml"] },
      { name: "Rice Bran Oil", unit: "litre", altUnits: ["ml"] },
      { name: "Ghee", unit: "litre", altUnits: ["kg", "ml"] },
      { name: "Rice (Chawal)", unit: "kg" },
      { name: "Broken Rice", unit: "kg" },
      { name: "Poha / Chuda (Flattened Rice)", unit: "kg" },
      { name: "Wheat Flour (Atta)", unit: "kg" },
      { name: "Maida (Refined Flour)", unit: "kg" },
      { name: "Sooji / Rava (Semolina)", unit: "kg" },
      { name: "Besan (Gram Flour)", unit: "kg" },
      { name: "Corn Flour", unit: "kg" },
      { name: "Rice Flour (Chawal Atta)", unit: "kg" },
      { name: "Sattu", unit: "kg" },
      { name: "Vermicelli (Sewai)", unit: "kg" },
      { name: "Sabudana / Sago", unit: "kg" },
      { name: "Noodles", unit: "kg" },
      { name: "Arhar / Toor Dal", unit: "kg" },
      { name: "Chana Dal", unit: "kg" },
      { name: "Moong Dal (Split)", unit: "kg" },
      { name: "Moong Dal (Whole)", unit: "kg" },
      { name: "Masoor Dal (Red Lentil)", unit: "kg" },
      { name: "Urad Dal (Split)", unit: "kg" },
      { name: "Urad Dal (Whole / Kala Dal)", unit: "kg" },
      { name: "Rajma (Kidney Beans)", unit: "kg" },
      { name: "Kabuli Chana / Chole", unit: "kg" },
      { name: "Kala Chana (Black Chickpea)", unit: "kg" },
      { name: "Lobia (Black-eyed Peas)", unit: "kg" },
      { name: "Sugar (Chini)", unit: "kg" },
      { name: "Jaggery (Gud)", unit: "kg" },
      { name: "Honey (Shahad)", unit: "litre", altUnits: ["ml"] },
      { name: "Salt (Namak)", unit: "kg" },
      { name: "Black Salt (Kala Namak)", unit: "kg" },
      { name: "Rock Salt (Sendha Namak)", unit: "kg" },
      { name: "Charmagaz (Watermelon Seeds)", unit: "kg" },
      { name: "Khus Khus / Poppy Seeds", unit: "kg" },
      { name: "Sesame Seeds (Til)", unit: "kg" },
      { name: "Peanuts (Moongphali)", unit: "kg" },
      { name: "Cashews (Kaju)", unit: "kg" },
      { name: "Almonds (Badam)", unit: "kg" },
      { name: "Raisins (Kishmish)", unit: "kg" },
      { name: "Walnuts (Akhrot)", unit: "kg" },
      { name: "Pistachios (Pista)", unit: "kg" },
      { name: "Dried Coconut (Copra)", unit: "kg" },
      { name: "Coconut (Nariyal)", unit: "pcs" },
      { name: "Cumin Seeds (Jeera)", unit: "kg" },
      { name: "Mustard Seeds (Rai)", unit: "kg" },
      { name: "Coriander Seeds (Sabut Dhania)", unit: "kg" },
      { name: "Fenugreek Seeds (Methi Dana)", unit: "kg" },
      { name: "Carom Seeds (Ajwain)", unit: "kg" },
      { name: "Black Pepper (Kali Mirch)", unit: "kg" },
      { name: "Green Cardamom (Elaichi)", unit: "kg" },
      { name: "Black Cardamom (Badi Elaichi)", unit: "kg" },
      { name: "Cloves (Laung)", unit: "kg" },
      { name: "Cinnamon (Dalchini)", unit: "kg" },
      { name: "Bay Leaves (Tej Patta)", unit: "kg" },
      { name: "Star Anise (Chakra Phool)", unit: "kg" },
      { name: "Mace (Javitri)", unit: "kg" },
      { name: "Nutmeg (Jaiphal)", unit: "pcs", altUnits: ["kg"] },
      { name: "Dried Red Chilli (Sabut Lal Mirch)", unit: "kg" },
      { name: "Asafoetida (Hing)", unit: "kg" },
      { name: "Kalonji / Nigella Seeds", unit: "kg" },
      { name: "Panch Phoron (Odia 5-spice)", unit: "kg" },
      { name: "Turmeric Powder (Haldi)", unit: "kg" },
      { name: "Red Chilli Powder (Lal Mirch)", unit: "kg" },
      { name: "Coriander Powder (Dhania Powder)", unit: "kg" },
      { name: "Cumin Powder (Jeera Powder)", unit: "kg" },
      { name: "Garam Masala", unit: "kg" },
      { name: "Biryani Masala", unit: "kg" },
      { name: "Chicken Masala", unit: "kg" },
      { name: "Pav Bhaji Masala", unit: "kg" },
      { name: "Chaat Masala", unit: "kg" },
      { name: "Sambar Powder", unit: "kg" },
      { name: "Kitchen King Masala", unit: "kg" },
      { name: "Dried Mango Powder (Amchur)", unit: "kg" },
      { name: "Tamarind (Imli)", unit: "kg" },
      { name: "Tomato Ketchup", unit: "litre", altUnits: ["kg"] },
      { name: "Soy Sauce", unit: "litre", altUnits: ["ml"] },
      { name: "Chilli Sauce", unit: "litre", altUnits: ["ml"] },
      { name: "Vinegar (Sirka)", unit: "litre", altUnits: ["ml"] },
      { name: "Mayonnaise", unit: "kg", altUnits: ["litre"] },
      { name: "Baking Soda (Meetha Soda)", unit: "kg" },
      { name: "Baking Powder", unit: "kg" },
      { name: "Cocoa Powder", unit: "kg" },
      { name: "Tea (Chai Patti)", unit: "kg" },
      { name: "Coffee Powder", unit: "kg" },
      { name: "Saffron (Kesar)", unit: "g", altUnits: ["kg"] },
      { name: "Rose Water (Gulab Jal)", unit: "litre", altUnits: ["ml"] },
    ],
  },

  {
    id: "dairy",
    label: "Dairy & Eggs",
    emoji: "🥛",
    color: "bg-blue-100 text-blue-800",
    borderColor: "border-blue-300",
    items: [
      { name: "Milk (Full Cream)", unit: "litre" },
      { name: "Milk (Toned)", unit: "litre" },
      { name: "Buffalo Milk", unit: "litre" },
      { name: "Paneer (Cottage Cheese)", unit: "kg" },
      { name: "Curd / Yogurt (Dahi)", unit: "kg" },
      { name: "Butter", unit: "kg" },
      { name: "Ghee (Desi)", unit: "litre", altUnits: ["kg"] },
      { name: "Cream (Malai)", unit: "litre", altUnits: ["kg"] },
      { name: "Khoya / Mawa", unit: "kg" },
      { name: "Buttermilk (Chaas)", unit: "litre" },
      { name: "Condensed Milk", unit: "litre", altUnits: ["kg"] },
      { name: "Skimmed Milk Powder", unit: "kg" },
      { name: "Cheese (Processed)", unit: "kg" },
      { name: "Rabri", unit: "kg" },
      { name: "Eggs (Anda)", unit: "dozen", altUnits: ["pcs", "tray"] },
    ],
  },

  {
    id: "non_veg",
    label: "Non-Veg",
    emoji: "🍗",
    color: "bg-red-100 text-red-800",
    borderColor: "border-red-300",
    items: [
      // Fish
      { name: "Rohu Fish (Rohi)", unit: "kg" },
      { name: "Catla Fish", unit: "kg" },
      { name: "Hilsa (Ilish / Ilishi)", unit: "kg" },
      { name: "Pomfret (Pomphret)", unit: "kg" },
      { name: "Mackerel (Bangda)", unit: "kg" },
      { name: "Sardine (Sardine)", unit: "kg" },
      { name: "Tilapia", unit: "kg" },
      { name: "Surmai (King Fish)", unit: "kg" },
      { name: "Salmon", unit: "kg" },
      { name: "Tuna", unit: "kg" },
      { name: "Dried Fish (Sukhila Macha)", unit: "kg" },
      { name: "Fish — Other (specify in notes)", unit: "kg" },
      // Seafood
      { name: "Prawn / Shrimp (Chingudi)", unit: "kg" },
      { name: "Tiger Prawn", unit: "kg" },
      { name: "Crab (Kankada)", unit: "kg" },
      { name: "Lobster", unit: "kg" },
      { name: "Squid / Calamari", unit: "kg" },
      { name: "Clams / Mussels (Shellfish)", unit: "kg" },
      { name: "Oyster", unit: "kg" },
      // Chicken
      { name: "Chicken (Whole / Live)", unit: "kg" },
      { name: "Chicken (Dressed / Clean)", unit: "kg" },
      { name: "Chicken Breast (Boneless)", unit: "kg" },
      { name: "Chicken Legs / Drumstick", unit: "kg" },
      { name: "Chicken Wings", unit: "kg" },
      { name: "Chicken Keema (Minced)", unit: "kg" },
      { name: "Chicken Liver (Kaleja)", unit: "kg" },
      // Mutton
      { name: "Mutton (Goat / Bakra)", unit: "kg" },
      { name: "Mutton Keema (Minced)", unit: "kg" },
      { name: "Mutton Liver", unit: "kg" },
      { name: "Mutton Bone (for curry)", unit: "kg" },
      // Pork
      { name: "Pork (Pork Meat)", unit: "kg" },
      { name: "Pork Keema", unit: "kg" },
      // Other
      { name: "Duck (Batakh)", unit: "kg" },
      { name: "Quail (Bater)", unit: "kg" },
    ],
  },

  {
    id: "utilities",
    label: "Utilities",
    emoji: "⚡",
    color: "bg-amber-100 text-amber-800",
    borderColor: "border-amber-300",
    items: [
      { name: "Electricity Bill", unit: "month" },
      { name: "Water Bill", unit: "month" },
      { name: "Internet / WiFi Bill", unit: "month" },
      { name: "LPG Gas Cylinder", unit: "cylinder", altUnits: ["kg"] },
      { name: "PNG Gas Bill (Piped)", unit: "month" },
      { name: "Mobile / Phone Bill", unit: "month" },
      { name: "Cable TV Bill", unit: "month" },
      { name: "Garbage Collection Fee", unit: "month" },
      { name: "Water Tanker", unit: "tanker" },
      { name: "Fuel (Diesel / Petrol)", unit: "litre" },
      { name: "Generator Fuel", unit: "litre" },
      { name: "Pest Control", unit: "service" },
    ],
  },

  {
    id: "rent",
    label: "Rent",
    emoji: "🏠",
    color: "bg-purple-100 text-purple-800",
    borderColor: "border-purple-300",
    items: [
      { name: "Hotel / Restaurant Rent", unit: "month" },
      { name: "Kitchen Space Rent", unit: "month" },
      { name: "Storage / Godown Rent", unit: "month" },
      { name: "Vehicle Rent", unit: "day", altUnits: ["month"] },
      { name: "Equipment Rent", unit: "day", altUnits: ["month"] },
      { name: "Parking Space Rent", unit: "month" },
    ],
  },

  {
    id: "staff_salary",
    label: "Staff Salary",
    emoji: "👨‍🍳",
    color: "bg-indigo-100 text-indigo-800",
    borderColor: "border-indigo-300",
    items: [
      { name: "Chef / Cook Salary", unit: "month" },
      { name: "Waiter / Server Salary", unit: "month" },
      { name: "Kitchen Helper Salary", unit: "month" },
      { name: "Cashier / Biller Salary", unit: "month" },
      { name: "Manager Salary", unit: "month" },
      { name: "Cleaner / Sweeper Salary", unit: "month" },
      { name: "Security Guard Salary", unit: "month" },
      { name: "Delivery Boy Salary", unit: "month" },
      { name: "Driver Salary", unit: "month" },
      { name: "Contract Labour", unit: "day", altUnits: ["week", "month"] },
    ],
  },

  {
    id: "maintenance",
    label: "Maintenance & Repair",
    emoji: "🔧",
    color: "bg-rose-100 text-rose-800",
    borderColor: "border-rose-300",
    items: [
      { name: "Equipment Repair", unit: "service" },
      { name: "Electrical Repair", unit: "service" },
      { name: "Plumbing Repair", unit: "service" },
      { name: "AC Servicing / Repair", unit: "service" },
      { name: "Refrigerator / Cooler Repair", unit: "service" },
      { name: "Furniture Repair", unit: "service" },
      { name: "Painting / Whitewash", unit: "service" },
      { name: "Chimney / Exhaust Cleaning", unit: "service" },
      { name: "Inverter / Battery Service", unit: "service" },
      { name: "Deep Cleaning", unit: "service" },
    ],
  },

  {
    id: "supplies",
    label: "Supplies & Packaging",
    emoji: "📦",
    color: "bg-orange-100 text-orange-800",
    borderColor: "border-orange-300",
    items: [
      { name: "Disposable Plates (Areca / Paper)", unit: "pcs", altUnits: ["pack", "dozen"] },
      { name: "Disposable Cups", unit: "pcs", altUnits: ["pack"] },
      { name: "Takeaway Boxes (Parcel Box)", unit: "pcs", altUnits: ["pack"] },
      { name: "Paper Bags", unit: "pcs", altUnits: ["pack"] },
      { name: "Aluminium Foil", unit: "roll", altUnits: ["kg"] },
      { name: "Cling Wrap", unit: "roll" },
      { name: "Tissue Paper / Napkins", unit: "pack" },
      { name: "Toothpicks", unit: "box" },
      { name: "Straws", unit: "pack" },
      { name: "Gloves (Kitchen)", unit: "box", altUnits: ["pcs"] },
      { name: "Aprons / Chef Coat", unit: "pcs" },
      { name: "Twine / Packing Thread", unit: "roll" },
    ],
  },

  {
    id: "cleaning",
    label: "Cleaning Supplies",
    emoji: "🧹",
    color: "bg-teal-100 text-teal-800",
    borderColor: "border-teal-300",
    items: [
      { name: "Dish Wash Liquid", unit: "litre", altUnits: ["ml"] },
      { name: "Dish Wash Bar / Vim", unit: "pcs" },
      { name: "Floor Cleaner (Phenyl / Lizol)", unit: "litre" },
      { name: "Toilet Cleaner (Harpic)", unit: "litre" },
      { name: "Glass Cleaner (Colin)", unit: "litre" },
      { name: "Bleaching Powder", unit: "kg" },
      { name: "Sanitizer", unit: "litre" },
      { name: "Washing Powder (Surf / Detergent)", unit: "kg" },
      { name: "Soap Bar (Laundry)", unit: "pcs" },
      { name: "Scrubber / Scotch Brite", unit: "pcs", altUnits: ["pack"] },
      { name: "Mop / Broom (Jhadoo)", unit: "pcs" },
      { name: "Dustbin Bags (Garbage Bags)", unit: "pack" },
    ],
  },

  {
    id: "procured",
    label: "Procured Items",
    emoji: "🥡",
    color: "bg-pink-100 text-pink-800",
    borderColor: "border-pink-300",
    items: [
      // Momos & Dumplings
      { name: "Momos (Veg)", unit: "kg", altUnits: ["pcs", "dozen"] },
      { name: "Momos (Chicken)", unit: "kg", altUnits: ["pcs", "dozen"] },
      { name: "Momos (Pork)", unit: "kg", altUnits: ["pcs", "dozen"] },
      { name: "Fried Momos", unit: "kg", altUnits: ["pcs", "dozen"] },
      // Breads & Bakery
      { name: "Bread (Sandwich Loaf)", unit: "loaf", altUnits: ["pcs"] },
      { name: "Brown Bread", unit: "loaf" },
      { name: "Burger Buns", unit: "pcs", altUnits: ["dozen", "pack"] },
      { name: "Dinner Rolls / Pav", unit: "pcs", altUnits: ["dozen"] },
      { name: "Naan / Kulcha (from supplier)", unit: "pcs", altUnits: ["dozen"] },
      { name: "Roti / Chapati (from supplier)", unit: "pcs", altUnits: ["dozen"] },
      { name: "Paratha (from supplier)", unit: "pcs", altUnits: ["dozen"] },
      { name: "Rusks / Toast", unit: "pack" },
      { name: "Pita Bread", unit: "pcs" },
      // Batters
      { name: "Idli / Dosa Batter", unit: "kg", altUnits: ["litre"] },
      // Frozen / Ready snacks
      { name: "Frozen Samosa", unit: "pcs", altUnits: ["kg"] },
      { name: "Frozen Cutlet / Patty", unit: "pcs", altUnits: ["kg"] },
      { name: "Frozen Spring Roll", unit: "pcs", altUnits: ["kg"] },
      { name: "Frozen French Fries", unit: "kg" },
      { name: "Paneer (Market / Supplier)", unit: "kg" },
      { name: "Tofu", unit: "kg" },
      // Sweets & Desserts (procured)
      { name: "Ice Cream (Bulk)", unit: "litre", altUnits: ["kg"] },
      { name: "Sweets / Mithai (Bulk)", unit: "kg" },
      { name: "Gulab Jamun Mix", unit: "kg" },
      { name: "Rasgulla (from supplier)", unit: "kg", altUnits: ["pcs"] },
      { name: "Cake / Pastry (from bakery)", unit: "pcs", altUnits: ["kg"] },
      // Pickles & Condiments (procured)
      { name: "Pickle (Achar) — Bulk", unit: "kg" },
      { name: "Papad (Bulk)", unit: "pack", altUnits: ["kg"] },
      { name: "Chutney (Packaged)", unit: "kg" },
      // Noodles & Pasta
      { name: "Pasta / Macaroni", unit: "kg" },
      { name: "Ramen / Instant Noodles", unit: "pack" },
    ],
  },

  {
    id: "beverages",
    label: "Beverages",
    emoji: "🥤",
    color: "bg-sky-100 text-sky-800",
    borderColor: "border-sky-300",
    items: [
      // Packaged drinks
      { name: "Mineral Water (Small 500ml)", unit: "bottle", altUnits: ["pcs"] },
      { name: "Mineral Water (1 Litre)", unit: "bottle", altUnits: ["pcs"] },
      { name: "Water Can (20 Litre)", unit: "can" },
      { name: "Soda Water", unit: "bottle", altUnits: ["litre"] },
      { name: "Cola (Pepsi / Coke)", unit: "bottle", altUnits: ["can", "litre"] },
      { name: "Lemon Soda (Limca / Sprite)", unit: "bottle", altUnits: ["can"] },
      { name: "Orange Soda (Fanta / Mirinda)", unit: "bottle", altUnits: ["can"] },
      { name: "Mango Drink (Maaza / Slice / Frooti)", unit: "bottle", altUnits: ["can", "litre"] },
      { name: "Packaged Juice (Mixed Fruit)", unit: "litre", altUnits: ["ml", "pack"] },
      { name: "Packaged Juice (Orange)", unit: "litre", altUnits: ["ml"] },
      { name: "Packaged Juice (Mango)", unit: "litre", altUnits: ["ml"] },
      { name: "Coconut Water (Packaged)", unit: "can", altUnits: ["pcs"] },
      { name: "Energy Drink (Red Bull / Monster)", unit: "can" },
      { name: "Iced Tea (Packaged)", unit: "bottle", altUnits: ["litre"] },
      // Syrups / Concentrates
      { name: "Rooh Afza / Rose Syrup", unit: "litre", altUnits: ["ml"] },
      { name: "Lemon Squash / Concentrate", unit: "litre", altUnits: ["ml"] },
      { name: "Sharbat Syrup", unit: "litre" },
      // Hot beverages
      { name: "Tea Bags (Lipton etc)", unit: "box", altUnits: ["pcs"] },
      { name: "Instant Coffee (Nescafe etc)", unit: "kg", altUnits: ["g"] },
      { name: "Horlicks / Bournvita", unit: "kg" },
    ],
  },

  {
    id: "miscellaneous",
    label: "Miscellaneous",
    emoji: "📋",
    color: "bg-slate-100 text-slate-700",
    borderColor: "border-slate-300",
    items: [
      { name: "Pamphlet / Flyer Printing", unit: "pcs" },
      { name: "Banner / Flex Print", unit: "pcs" },
      { name: "Online Advertising", unit: "campaign" },
      { name: "Swiggy / Zomato Commission", unit: "month" },
      { name: "Stationery (Pen, Paper)", unit: "pack" },
      { name: "Newspaper", unit: "month" },
      { name: "First Aid Kit / Medicine", unit: "pcs" },
      { name: "Insurance Premium", unit: "year", altUnits: ["month"] },
      { name: "Bank Charges / Fees", unit: "month" },
      { name: "Tax / Professional Tax", unit: "month" },
      { name: "Loan EMI", unit: "month" },
      { name: "Other", unit: "pcs" },
    ],
  },
];

export const ALL_UNITS = [
  "kg", "g", "litre", "ml", "pcs", "dozen", "tray",
  "bundle", "box", "bag", "roll", "pack", "cylinder",
  "service", "month", "day", "week", "year", "unit",
  "tanker", "campaign", "quintal", "loaf", "bottle",
  "can", "carton",
];

export const CATALOG_MAP = Object.fromEntries(EXPENSE_CATALOG.map((c) => [c.id, c]));

export const ALL_CATALOG_ITEMS = EXPENSE_CATALOG.flatMap((cat) =>
  cat.items.map((item) => ({ ...item, categoryId: cat.id, categoryLabel: cat.label, categoryEmoji: cat.emoji }))
);
